import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import RootLayout from "@/components/Layouts/RootLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech-Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/logo-1.png" />
      </Head>
      <main className={`${styles.main}`}>

        <div className={styles.heroSection}>
          <div className={styles.overlay}></div>
          <div className={styles.content}>
            <h1>Welcome to TECH-HUB</h1>
            <p>Build your dream PC with our customizable options.</p>
          </div>
        </div>

        <div>

        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};
